# Generated by Django 5.0.2 on 2024-03-03 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('record', models.JSONField(blank=True, default=list)),
                ('conference', models.CharField(max_length=50)),
                ('standing', models.IntegerField(blank=True, null=True)),
                ('coach', models.CharField(max_length=120)),
                ('arena', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('PG', 'pg'), ('SG', 'sg'), ('SF', 'sf'), ('PF', 'pf'), ('C', 'c')], max_length=30, null=True)),
                ('ppg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trpg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
            ],
        ),
    ]
