# Generated by Django 5.0.2 on 2024-03-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_player_apg_alter_player_ppg_alter_player_trpg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
