# Generated by Django 5.0.2 on 2024-03-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
