# Generated by Django 5.0.2 on 2024-03-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
