# Generated by Django 5.0.2 on 2024-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_team_player_team_name_player_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
