# Generated by Django 5.0.2 on 2024-03-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=6)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('standing', models.IntegerField()),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gb', models.IntegerField(blank=True, null=True)),
                ('home_wins', models.IntegerField(blank=True, null=True)),
                ('home_losses', models.IntegerField(blank=True, null=True)),
                ('road_wins', models.IntegerField(blank=True, null=True)),
                ('road_losses', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='apg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='trpg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.record'),
        ),
    ]
