# Generated by Django 5.0.2 on 2024-03-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_record_alter_player_apg_alter_player_ppg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
