# Generated by Django 5.0.2 on 2024-03-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_record_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='record',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
