# Generated by Django 5.0.2 on 2024-03-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_team_record_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=6, null=True)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('standing', models.IntegerField()),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gb', models.IntegerField(blank=True, null=True)),
                ('home_wins', models.IntegerField(blank=True, null=True)),
                ('home_losses', models.IntegerField(blank=True, null=True)),
                ('road_wins', models.IntegerField(blank=True, null=True)),
                ('road_losses', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
