# Generated by Django 5.0.2 on 2024-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, choices=[('East', 'east'), ('West', 'west')], max_length=50, null=True),
        ),
    ]
