# Generated by Django 5.0.2 on 2024-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_team_abbreviation_team_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
