# Generated by Django 5.0.2 on 2024-03-29 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_record_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('mins', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ppg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('drpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('orpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ftpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ftpc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fgpc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('treypc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='apg',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ppg',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trpg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='standing',
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stats'),
        ),
    ]
