# Generated by Django 5.0.2 on 2024-03-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_stats_remove_player_apg_remove_player_ppg_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
