# Generated by Django 5.0.2 on 2024-04-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_playoffgame_playoffseries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayoffSeries',
            new_name='PlayoffSerie',
        ),
    ]
