# Generated by Django 5.0.2 on 2024-04-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_playoffserie_playoffseries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffgame',
            name='elimination',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='playoffgame',
            name='game_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playoffseries',
            name='finals',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='PlayoffTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrv', models.CharField(blank=True, max_length=6, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team')),
            ],
        ),
        migrations.AlterField(
            model_name='playoffgame',
            name='away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='api.playoffteam'),
        ),
        migrations.AlterField(
            model_name='playoffgame',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='api.playoffteam'),
        ),
        migrations.AlterField(
            model_name='playoffseries',
            name='high_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_seed_series', to='api.playoffteam'),
        ),
        migrations.AlterField(
            model_name='playoffseries',
            name='low_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_seed_series', to='api.playoffteam'),
        ),
    ]
