# Generated by Django 5.0.2 on 2024-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
