# Generated by Django 5.0.2 on 2024-07-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_player_birthdate_player_country_player_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='school',
            new_name='college',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
